### ISSUE TITLE
无法读取auth.json文件

### ISSUE THREAD

**Issue by zhizhi0225** [colakele/JDC-kele#6]
大佬，我的ql/config/auth.json文件一直都在呀，为什么一直提示这个错误，文件读取权限也全开了。
![image](https://user-images.githubusercontent.com/56391314/123114460-e5feb500-d471-11eb-86a1-65ed31c71c13.png)
![image](https://user-images.githubusercontent.com/56391314/123114662-0fb7dc00-d472-11eb-857e-fcec2066a9c3.png)

**Comment by colakele** [comment]
路径不对，你这是/root/ql/config/

**Comment by zhizhi0225** [comment]
好的大佬，重装一下改了个路径解决了，感谢
